In [1]:
import tensorflow as tf
import numpy as np

C:\ai\python\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\ai\python\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\ai\python\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\ai\python\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type

In [2]:
tf.enable_eager_execution()

In [11]:
X = np.array([1,2,3], dtype='float32')
X

array([1., 2., 3.], dtype=float32)

In [12]:
y = np.array([2.5,5,3.5], dtype='float32')
y

array([2.5, 5. , 3.5], dtype=float32)

In [13]:
w = tf.Variable([2], dtype='float32')
b = tf.Variable([1], dtype='float32')

In [14]:
w

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.], dtype=float32)>

In [15]:
b

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.], dtype=float32)>

In [16]:
hypothesis = w*X+b
hypothesis

<tf.Tensor: id=47048, shape=(3,), dtype=float32, numpy=array([3., 5., 7.], dtype=float32)>

In [17]:
tf.square(hypothesis-y)

<tf.Tensor: id=47052, shape=(3,), dtype=float32, numpy=array([ 0.25,  0.  , 12.25], dtype=float32)>

In [19]:
tf.reduce_mean(tf.square(hypothesis-y))

<tf.Tensor: id=47063, shape=(), dtype=float32, numpy=4.1666665>

In [8]:
learning_rate = 0.1

In [21]:
for i in range(1000):
    with tf.GradientTape() as tape:
        hypothesis = w*X+b
        print('hypothesis : ',hypothesis)
        cost = tf.reduce_mean(tf.square(hypothesis-y))
        print('cost : ',cost)
    w_grad,b_grad = tape.gradient(cost,[w,b])
    print('w_grad : ',w_grad,'b_grad : ',b_grad)
    w.assign_sub(w_grad*learning_rate)
    b.assign_sub(b_grad*learning_rate)
    print('w : ',w)
    print('b : ',b)
    print('--'*40)

hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=flo

cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
-----------------------------------------------------------------------------

w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shap

hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=flo

w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shap

cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
-----------------------------------------------------------------------------

w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shap

w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.16

w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shap

w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.16

w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.16

w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.16

w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shap

b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Va

w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.16

w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.16

w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.16

w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.16

w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shap

w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shap

w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.16

w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shap

hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=flo

w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.16

cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
-----------------------------------------------------------------------------

w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shap

hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=flo

w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.16

b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Va

cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
-----------------------------------------------------------------------------

w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.16

w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shap

w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.16

cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
-----------------------------------------------------------------------------

b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.50000185], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.6666625], dtype=float32)>
--------------------------------------------------------------------------------
hypothesis :  tf.Tensor([3.1666644 3.666666  4.166668 ], shape=(3,), dtype=float32)
cost :  tf.Tensor(0.888889, shape=(), dtype=float32)
w_grad :  tf.Tensor([2.3841858e-07], shape=(1,), dtype=float32) b_grad :  tf.Tensor([-1.0728836e-06], shape=(1,), dtype=float32)
w :  <tf.Va

In [28]:
print(w.numpy()[0])
print(b.numpy()[0])
print(cost.numpy())

0.50000185
2.6666625
0.888889


In [29]:
10*w+b

<tf.Tensor: id=149096, shape=(1,), dtype=float32, numpy=array([7.6666813], dtype=float32)>