In [1]:
import numpy as np
import tensorflow as tf

C:\ai\python\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\ai\python\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\ai\python\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\ai\python\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type

In [2]:
tf.enable_eager_execution()

In [3]:
X=np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
], dtype='float32')
y=np.array([
    [0],
    [1],
    [1],
    [0]
], dtype='float32')

In [4]:
X.shape

(4, 2)

In [5]:
y.shape

(4, 1)

In [6]:
w0 = tf.Variable([
    [1,2],
    [3,4]
], dtype='float32')
w0

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [7]:
b0= tf.Variable([[0,0]],dtype='float32')
b0

<tf.Variable 'Variable:0' shape=(1, 2) dtype=float32, numpy=array([[0., 0.]], dtype=float32)>

In [8]:
arr = np.array([
    [0,1]
], dtype='float32')
arr

array([[0., 1.]], dtype=float32)

In [9]:
tf.matmul(arr,w0)+b0

<tf.Tensor: id=23, shape=(1, 2), dtype=float32, numpy=array([[3., 4.]], dtype=float32)>

In [10]:
hypothesis0 = tf.sigmoid(tf.matmul(arr,w0)+b0)
hypothesis0

<tf.Tensor: id=30, shape=(1, 2), dtype=float32, numpy=array([[0.95257413, 0.98201376]], dtype=float32)>

In [11]:
w1 = tf.Variable([
    [5],
    [6]
],dtype='float32')
w1

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[5.],
       [6.]], dtype=float32)>

In [12]:
b1=tf.Variable([[0]],dtype='float32')
b1

<tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[0.]], dtype=float32)>

In [13]:
tf.matmul(hypothesis0,w1)+b1

<tf.Tensor: id=53, shape=(1, 1), dtype=float32, numpy=array([[10.654953]], dtype=float32)>

In [14]:
hypothesis1 = tf.sigmoid(tf.matmul(hypothesis0,w1)+b1)
hypothesis1

<tf.Tensor: id=59, shape=(1, 1), dtype=float32, numpy=array([[0.9999764]], dtype=float32)>

In [15]:
hy0=tf.sigmoid(tf.matmul(X,w0)+b0)
hy0

<tf.Tensor: id=66, shape=(4, 2), dtype=float32, numpy=
array([[0.5       , 0.5       ],
       [0.95257413, 0.98201376],
       [0.7310586 , 0.8807971 ],
       [0.98201376, 0.99752736]], dtype=float32)>

In [16]:
tf.sigmoid(tf.matmul(hy0,w1)+b1)

<tf.Tensor: id=72, shape=(4, 1), dtype=float32, numpy=
array([[0.9959299],
       [0.9999764],
       [0.9998689],
       [0.9999814]], dtype=float32)>

In [17]:
optimizer = tf.train.AdamOptimizer(0.01)

In [21]:
for i in range(4000):
    with tf.GradientTape() as tape:
        hypothesis0 = tf.sigmoid(tf.matmul(X,w0)+b0)
        hypothesis1 = tf.sigmoid(tf.matmul(hypothesis0,w1)+b1)
        cost = -tf.reduce_mean(y*tf.log(hypothesis1)+(1-y)*tf.log(1-hypothesis1))
        grad = tape.gradient(cost,[w0,w1,b0,b1])
        optimizer.apply_gradients(grads_and_vars=zip(grad,[w0,w1,b0,b1]))
    if i%100 == 0:
        print(f'cost{i}',cost)


cost0 tf.Tensor(0.0028543188, shape=(), dtype=float32)
cost100 tf.Tensor(0.002471028, shape=(), dtype=float32)
cost200 tf.Tensor(0.0021659306, shape=(), dtype=float32)
cost300 tf.Tensor(0.001917483, shape=(), dtype=float32)
cost400 tf.Tensor(0.0017114708, shape=(), dtype=float32)
cost500 tf.Tensor(0.0015379646, shape=(), dtype=float32)
cost600 tf.Tensor(0.0013899946, shape=(), dtype=float32)
cost700 tf.Tensor(0.0012624968, shape=(), dtype=float32)
cost800 tf.Tensor(0.0011515035, shape=(), dtype=float32)
cost900 tf.Tensor(0.0010541854, shape=(), dtype=float32)
cost1000 tf.Tensor(0.0009682233, shape=(), dtype=float32)
cost1100 tf.Tensor(0.0008918368, shape=(), dtype=float32)
cost1200 tf.Tensor(0.00082360546, shape=(), dtype=float32)
cost1300 tf.Tensor(0.00076231826, shape=(), dtype=float32)
cost1400 tf.Tensor(0.00070703326, shape=(), dtype=float32)
cost1500 tf.Tensor(0.00065698836, shape=(), dtype=float32)
cost1600 tf.Tensor(0.0006115411, shape=(), dtype=float32)
cost1700 tf.Tensor(0.000

In [22]:
w0

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ -6.916672, -14.155371],
       [  7.791381,  14.795871]], dtype=float32)>

In [23]:
w1

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[-18.077158],
       [ 20.4327  ]], dtype=float32)>

In [24]:
b0

<tf.Variable 'Variable:0' shape=(1, 2) dtype=float32, numpy=array([[ 3.0277085, -8.93653  ]], dtype=float32)>

In [25]:
b1

<tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[8.49174]], dtype=float32)>

In [26]:
hy = tf.sigmoid(tf.matmul(X,w0)+b0)
hy

<tf.Tensor: id=1376334, shape=(4, 2), dtype=float32, numpy=
array([[9.5381033e-01, 1.3148785e-04],
       [9.9997997e-01, 9.9715495e-01],
       [2.0056099e-02, 0.0000000e+00],
       [9.8020667e-01, 2.4944544e-04]], dtype=float32)>

In [29]:
predict=tf.sigmoid(tf.matmul(hy,w1)+b1)
predict

<tf.Tensor: id=1376351, shape=(4, 1), dtype=float32, numpy=
array([[1.5887618e-04],
       [9.9997938e-01],
       [9.9970520e-01],
       [9.8794699e-05]], dtype=float32)>

In [31]:
predict01 = tf.cast(predict>0.5,dtype='float32')
predict01

<tf.Tensor: id=1376356, shape=(4, 1), dtype=float32, numpy=
array([[0.],
       [1.],
       [1.],
       [0.]], dtype=float32)>