In [30]:
import tensorflow as tf
import numpy as np

In [31]:
tf.enable_eager_execution()

In [32]:
X = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]], dtype='float32'
)
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [33]:
y=np.array([
    [0],
    [0],
    [0],
    [1]],dtype='float32')
y

array([[0.],
       [0.],
       [0.],
       [1.]], dtype=float32)

In [34]:
w=tf.Variable([
    [1],
    [2]
], dtype='float32')
w

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[1.],
       [2.]], dtype=float32)>

In [35]:
X[3]

array([1., 1.], dtype=float32)

In [36]:
X[3]*w

<tf.Tensor: id=33178, shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [2., 2.]], dtype=float32)>

In [37]:
tf.matmul(X,w)

<tf.Tensor: id=33182, shape=(4, 1), dtype=float32, numpy=
array([[0.],
       [2.],
       [1.],
       [3.]], dtype=float32)>

In [38]:
tf.matmul(np.array([
    [1,1]
],dtype='float32'),w)

<tf.Tensor: id=33186, shape=(1, 1), dtype=float32, numpy=array([[3.]], dtype=float32)>

In [39]:
b=tf.Variable([3],dtype='float32')
b

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([3.], dtype=float32)>

In [40]:
tf.matmul(X,w)+b

<tf.Tensor: id=33201, shape=(4, 1), dtype=float32, numpy=
array([[3.],
       [5.],
       [4.],
       [6.]], dtype=float32)>

In [41]:
tf.sigmoid(tf.matmul(X,w)+b)

<tf.Tensor: id=33208, shape=(4, 1), dtype=float32, numpy=
array([[0.95257413],
       [0.9933071 ],
       [0.98201376],
       [0.99752736]], dtype=float32)>

In [42]:
optmizier = tf.train.AdamOptimizer(0.01)

In [43]:
for step in range(500):
    with tf.GradientTape() as tape:
        hypothesis = tf.sigmoid(tf.matmul(X,w)+b)
#        print('hypothesis : ',hypothesis)
        cost = -tf.reduce_mean(y*tf.log(hypothesis)+(1-y)*tf.log(1-hypothesis))
#        print('cost : ',cost)
        grads = tape.gradient(cost,[w,b])
#        print('grads : ',grads)
#        print('w : ',w) ## w1,w2 의 기울기 가 들어 있음
#        print('b : ',b) ## b 의 기울기 가 들어 있음
#        print('zip(grads,w,b) : ',list(zip(grads,[w,b]))) # zip은 grads, w,b,세개의 값을 압축해서 보여줌
    optmizier.apply_gradients(grads_and_vars=zip(grads,[w,b])) # learning rate를 곱해서 w와 b를 최신화(갱신)시켜줌
#    print('w_n : ',w) ## w1,w2 의 기울기 가 들어 있음
#    print('b_n : ',b) ## b 의 기울기 가 들어 있음

    if step % 100 == 0:
        print('-*-'*30)
        print(f"step:{step}, cost:{cost.numpy()}, w:{w.numpy()}, b:{b.numpy()}")
        


-*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*-
step:0, cost:3.0189805030822754, w:[[0.99]
 [1.99]], b:[2.99]
-*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*-
step:100, cost:1.8529284000396729, w:[[0.01112574]
 [1.0014889 ]], b:[2.0029898]
-*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*-
step:200, cost:1.0872455835342407, w:[[-0.71142066]
 [ 0.1846364 ]], b:[1.1350007]
-*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*-
step:300, cost:0.8457093834877014, w:[[-0.770385  ]
 [-0.11182883]], b:[0.52571815]
-*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*-
step:400, cost:0.7202606201171875, w:[[-0.4511011]
 [-0.0378984]], b:[0.06198945]


In [44]:
predict = tf.sigmoid(tf.matmul(X,w)+b)
predict

<tf.Tensor: id=66290, shape=(4, 1), dtype=float32, numpy=
array([[0.41256934],
       [0.45192403],
       [0.3944635 ],
       [0.43336523]], dtype=float32)>

In [45]:
predict01 = tf.cast(predict>0.5, dtype='float32')
predict01

<tf.Tensor: id=66294, shape=(4, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.]], dtype=float32)>

In [46]:
y

array([[0.],
       [0.],
       [0.],
       [1.]], dtype=float32)

In [47]:
ac01=tf.equal(predict01,y)
ac01

<tf.Tensor: id=66297, shape=(4, 1), dtype=bool, numpy=
array([[ True],
       [ True],
       [ True],
       [False]])>

In [48]:
ac02=tf.cast(ac01,dtype='float32')
ac02

<tf.Tensor: id=66299, shape=(4, 1), dtype=float32, numpy=
array([[1.],
       [1.],
       [1.],
       [0.]], dtype=float32)>

In [49]:
ac03=tf.reduce_mean(ac02)
ac03

<tf.Tensor: id=66302, shape=(), dtype=float32, numpy=0.75>

In [50]:
accuracy = tf.reduce_mean(tf.cast(tf.equal(predict01,y),dtype='float32'))
# 위의 ac들을 한번에 계산
print('정확도 : ', accuracy.numpy()*100,'%')

정확도 :  75.0 %


# predict ~ accuracy의 이해

In [51]:
arr=np.array([
    [0.5,0.3]
], dtype='float32')
arr

array([[0.5, 0.3]], dtype=float32)

In [52]:
predict_n = tf.sigmoid(tf.matmul(arr,w)+b)
predict_n

<tf.Tensor: id=66315, shape=(1, 1), dtype=float32, numpy=array([[0.41512102]], dtype=float32)>

In [53]:
tf.cast(predict_n>0.5, dtype='float32')

<tf.Tensor: id=66319, shape=(1, 1), dtype=float32, numpy=array([[0.]], dtype=float32)>

In [54]:
arr=np.array([[1,1]],dtype='float32')

In [55]:
predict_n = tf.sigmoid(tf.matmul(arr,w)+b)
predict_n

<tf.Tensor: id=66326, shape=(1, 1), dtype=float32, numpy=array([[0.43336526]], dtype=float32)>

In [56]:
tf.cast(predict_n>0.5, dtype='float32')

<tf.Tensor: id=66330, shape=(1, 1), dtype=float32, numpy=array([[0.]], dtype=float32)>

# zip에 대한 이해

In [57]:
a_n=[1,2,3,8]
b_n=[100,200,300,400]
list(zip(a_n,b_n)) # a와 b를 같은 순서 끼리 합쳐주는 것


[(1, 100), (2, 200), (3, 300), (8, 400)]

In [58]:
grad=[['w1기울기','w2기울기'],['b기울기']]
w_n=['w1','w2']
b_n=['b']
print([w_n,b_n]) # w뒤에 b가 추가되는 형식으로 나옴
print(list(zip(grad,[w_n,b_n]))) # w의 기울기는 w와 b의 기울기는 b 와 대응되어 나옴

[['w1', 'w2'], ['b']]
[(['w1기울기', 'w2기울기'], ['w1', 'w2']), (['b기울기'], ['b'])]
