In [1]:
import numpy as np
import pandas as pd

In [4]:
data ={
    "X1":[0.2,0.45,0.33,0.54,0.77],
    "X2":[5.6,5.87,6.37,7.9,7.87],
    "X3":[3.56,2.4,1.95,1.32,0.98],
    "y":[100,70,60,45,30]
      }

In [7]:
df=pd.DataFrame(data)
df

X1    X2    X3    y
0  0.20  5.60  3.56  100
1  0.45  5.87  2.40   70
2  0.33  6.37  1.95   60
3  0.54  7.90  1.32   45
4  0.77  7.87  0.98   30

In [9]:
X = df[['X1','X2','X3']]
X

X1    X2    X3
0  0.20  5.60  3.56
1  0.45  5.87  2.40
2  0.33  6.37  1.95
3  0.54  7.90  1.32
4  0.77  7.87  0.98

In [11]:
y= df['y']
y

0    100
1     70
2     60
3     45
4     30
Name: y, dtype: int64

In [13]:
print(X.mean())
print(X.std())

X1    0.458
X2    6.722
X3    2.042
dtype: float64
X1    0.216264
X2    1.097073
X3    1.011197
dtype: float64


In [14]:
X=X-X.mean()

In [15]:
X=X/X.std()
X

X1        X2        X3
0 -1.192988 -1.022721  1.501191
1 -0.036992 -0.776612  0.354036
2 -0.591870 -0.320854 -0.090981
3  0.379167  1.073766 -0.714005
4  1.442683  1.046420 -1.050240

In [17]:
X_cov = np.dot(X.T, X)/15
X_cov

array([[ 0.26666667,  0.22370099, -0.23573601],
       [ 0.22370099,  0.26666667, -0.24311486],
       [-0.23573601, -0.24311486,  0.26666667]])

In [18]:
eigenvalue, eigenvector = np.linalg.eig(X_cov)
print('고유값: ', eigenvalue)
print('고유벡터 : \n',eigenvector)

고유값:  [0.73512513 0.04377061 0.02110426]
고유벡터 : 
 [[ 0.56993665  0.7754158   0.27185024]
 [ 0.57618187 -0.61301734  0.54057764]
 [-0.58582135  0.15145983  0.79616158]]


In [19]:
eigenvalue[0]

0.7351251269715192

In [20]:
sum(eigenvalue)

0.7999999999999996

In [21]:
eigenvalue[0]/sum(eigenvalue)

0.9189064087143994

In [22]:
z1 = X.dot(eigenvector.T[0])
z1

0   -2.148630
1   -0.675954
2   -0.468900
3    1.253065
4    2.040419
dtype: float64

In [23]:
from sklearn import linear_model
linear_regression = linear_model.LinearRegression()

In [24]:
linear_regression.fit(X=X, y=y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [25]:
linear_regression.score(X=X,y=y)

0.9978441052442628

In [26]:
linear_regression.fit(X=pd.DataFrame(z1), y=y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [27]:
linear_regression.score(X=pd.DataFrame(z1),y=y)

0.959290206663969