In [1]:
from math import e

In [2]:
e

2.718281828459045

In [3]:
print(e**-1)
print(e**0)

0.36787944117144233
1.0


In [5]:
print(1/(1+e**-(-5)))
print(1/(1+e**-(-2.5)))
print(1/(1+e**-(0)))
print(1/(1+e**-(2.5)))
print(1/(1+e**-(5)))

0.006692850924284857
0.07585818002124356
0.5
0.9241418199787566
0.9933071490757153


# 인공 신경망을 이용한 AND연산 (파이썬)

In [6]:
import numpy as np
import tensorflow as tf
tf.enable_eager_execution()

C:\ai\python\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\ai\python\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\ai\python\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\ai\python\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type

In [9]:
X=np.array([
            [0,0],
            [0,1],
            [1,0],
            [1,1]
], dtype='float32')
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [10]:
y=np.array([
            [0],
            [0],
            [0],
            [1]
], dtype='float32')
y

array([[0.],
       [0.],
       [0.],
       [1.]], dtype=float32)

In [11]:
w = np.array([[1],[2]], dtype='float32')
w

array([[1.],
       [2.]], dtype=float32)

In [12]:
b = np.array([3], dtype='float32')
b

array([3.], dtype=float32)

In [13]:
np.dot(X,w)

array([[0.],
       [2.],
       [1.],
       [3.]], dtype=float32)

In [14]:
np.dot(X,w)+b

array([[3.],
       [5.],
       [4.],
       [6.]], dtype=float32)

In [20]:
def sigmoid(h):
    return 1/(1+np.exp(-h))

In [21]:
hypothesis = np.dot(X,w)+b
hypothesis

array([[3.],
       [5.],
       [4.],
       [6.]], dtype=float32)

In [22]:
hypothesis = sigmoid(np.dot(X,w)+b)
hypothesis

array([[0.95257413],
       [0.9933072 ],
       [0.98201376],
       [0.9975274 ]], dtype=float32)

In [23]:
hypothesis-y

array([[ 0.95257413],
       [ 0.9933072 ],
       [ 0.98201376],
       [-0.00247258]], dtype=float32)

In [25]:
X.T

array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]], dtype=float32)

In [26]:
X.T[0]

array([0., 0., 1., 1.], dtype=float32)

In [46]:
X1=X.T[0].reshape(1,-1)
print(X1)
X2=X.T[1].reshape(1,4)
print(X2)

[[0. 0. 1. 1.]]
[[0. 1. 0. 1.]]


In [47]:
np.dot(X1,(hypothesis-y))

array([[0.9795412]], dtype=float32)

In [48]:
np.sum(np.dot(X1,(hypothesis-y)))

0.9795412

In [49]:
w1_gred=np.sum(np.dot(X1,(hypothesis-y)))/4
w1_gred

0.24488529562950134

In [50]:
w2_gred=np.sum(np.dot(X2,(hypothesis-y)))/4
w2_gred

0.24770864844322205

In [55]:
hypothesis-y

array([[ 0.95257413],
       [ 0.9933072 ],
       [ 0.98201376],
       [-0.00247258]], dtype=float32)

In [56]:
b_gred=np.sum(hypothesis-y)/4
b_gred

0.731355607509613

In [57]:
learning_rate = 0.1

In [67]:
for i in range(100):
    for j in range(2):
        hypothesis=sigmoid(np.dot(X,w)+b)
        print('hypothesis : ',hypothesis)
        cost=1/4*(-y*np.log(hypothesis))-((1-y)*np.log(1-hypothesis))
        print('cost : ',cost)
        X_col_2d=X.T[j].reshape(1,-1)
        w_gred = 1/4*np.sum(np.dot(X_col_2d,(hypothesis-y)))
        print(f'w_{i}gred : {w_gred}')
        w[j]=w[j]-learning_rate*w_gred
        print('w : ',w)
        b_gred=1/4*np.sum(hypothesis-y)
        print('b_gred : ',b_gred)
        b = b-learning_rate*b_gred
        print('b : ',b)

hypothesis :  [[0.330786  ]
 [0.3651863 ]
 [0.25163576]
 [0.28126436]]
cost :  [[0.40165138]
 [0.45442376]
 [0.2898655 ]
 [0.31711507]]
w_0gred : -0.11677496880292892
w :  [[-0.37359735]
 [ 0.1517085 ]]
b_gred :  0.057218119502067566
b :  [-0.71035415]
hypothesis :  [[0.32952058]
 [0.3638609 ]
 [0.25275895]
 [0.28246987]]
cost :  [[0.39976227]
 [0.45233804]
 [0.2913675 ]
 [0.31604585]]
w_0gred : -0.08841730654239655
w :  [[-0.37359735]
 [ 0.16055024]]
b_gred :  0.05715256929397583
b :  [-0.7160694]
hypothesis :  [[0.3282591 ]
 [0.36458486]
 [0.25168103]
 [0.283104  ]]
cost :  [[0.39788258]
 [0.45347673]
 [0.28992596]
 [0.31548524]]
w_1gred : -0.11630374193191528
w :  [[-0.36196697]
 [ 0.16055024]]
b_gred :  0.056907251477241516
b :  [-0.72176015]
hypothesis :  [[0.3270055 ]
 [0.36326757]
 [0.25280136]
 [0.28431103]]
cost :  [[0.39601812]
 [0.4514057 ]
 [0.2914242 ]
 [0.31442162]]
w_1gred : -0.08810534328222275
w :  [[-0.36196697]
 [ 0.16936077]]
b_gred :  0.056846365332603455
b :  [-0.

hypothesis :  [[0.2560319 ]
 [0.34692425]
 [0.25321382]
 [0.34356776]]
cost :  [[0.29575709]
 [0.42606214]
 [0.29197636]
 [0.26709273]]
w_34gred : -0.10080461204051971
w :  [[-0.00476795]
 [ 0.43410948]]
b_gred :  0.04993443191051483
b :  [-1.0716896]
hypothesis :  [[0.2550819 ]
 [0.34579375]
 [0.25417697]
 [0.34471598]]
cost :  [[0.29448098]
 [0.42433256]
 [0.29326695]
 [0.2662586 ]]
w_34gred : -0.07737257331609726
w :  [[-0.00476795]
 [ 0.44184673]]
b_gred :  0.04994213581085205
b :  [-1.0766838]
hypothesis :  [[0.2541341 ]
 [0.34641457]
 [0.2532314 ]
 [0.34533584]]
cost :  [[0.2932094 ]
 [0.42528203]
 [0.29199994]
 [0.26580948]]
w_35gred : -0.10035818815231323
w :  [[0.00526787]
 [0.44184673]]
b_gred :  0.04977896809577942
b :  [-1.0816617]
hypothesis :  [[0.25319168]
 [0.34528837]
 [0.25418904]
 [0.3464802 ]]
cost :  [[0.29194677]
 [0.42356044]
 [0.29328308]
 [0.2649824 ]]
w_35gred : -0.0770578607916832
w :  [[0.00526787]
 [0.4495525 ]]
b_gred :  0.04978732764720917
b :  [-1.086640

w_62gred : -0.06918351352214813
w :  [[0.2601919 ]
 [0.64630157]]
b_gred :  0.046070098876953125
b :  [-1.3447142]
hypothesis :  [[0.2067359 ]
 [0.33216426]
 [0.25265118]
 [0.392165  ]]
cost :  [[0.23159909]
 [0.40371308]
 [0.2912233 ]
 [0.23401815]]
w_63gred : -0.08879595249891281
w :  [[0.2690715 ]
 [0.64630157]]
b_gred :  0.045929089188575745
b :  [-1.3493071]
hypothesis :  [[0.20598368]
 [0.3311462 ]
 [0.25346145]
 [0.39318734]]
cost :  [[0.23065129]
 [0.40218985]
 [0.29230806]
 [0.23336726]]
w_63gred : -0.06891661137342453
w :  [[0.2690715 ]
 [0.65319324]]
b_gred :  0.04594467580318451
b :  [-1.3539015]
hypothesis :  [[0.20523326]
 [0.33165523]
 [0.25259307]
 [0.39373553]]
cost :  [[0.22970663]
 [0.40295118]
 [0.29114544]
 [0.23301896]]
w_64gred : -0.08841785043478012
w :  [[0.27791327]
 [0.65319324]]
b_gred :  0.04580426216125488
b :  [-1.3584819]
hypothesis :  [[0.20448716]
 [0.3306407 ]
 [0.25339845]
 [0.39475328]]
cost :  [[0.22876827]
 [0.40143424]
 [0.2922236 ]
 [0.23237358]

 [0.43345132]]
cost :  [[0.18509597]
 [0.3826922 ]
 [0.2879337 ]
 [0.20899394]]
w_91gred : -0.07909000664949417
w :  [[0.5032087]
 [0.8298226]]
b_gred :  0.04264816641807556
b :  [-1.5971707]
hypothesis :  [[0.16837741]
 [0.31705305]
 [0.25087294]
 [0.4343464 ]]
cost :  [[0.18437655]
 [0.38133815]
 [0.2888467 ]
 [0.20847823]]
w_91gred : -0.062150128185749054
w :  [[0.5032087 ]
 [0.83603764]]
b_gred :  0.042662471532821655
b :  [-1.601437]
hypothesis :  [[0.16778088]
 [0.31747517]
 [0.25007203]
 [0.43482527]]
cost :  [[0.18365951]
 [0.38195643]
 [0.28777808]
 [0.20820275]]
w_92gred : -0.07877566665410995
w :  [[0.5110863 ]
 [0.83603764]]
b_gred :  0.042538344860076904
b :  [-1.6056908]
hypothesis :  [[0.16718774]
 [0.31655413]
 [0.2507522 ]
 [0.43571597]]
cost :  [[0.18294705]
 [0.3806078 ]
 [0.28868553]
 [0.20769118]]
w_92gred : -0.06193247437477112
w :  [[0.5110863 ]
 [0.84223086]]
b_gred :  0.04255251586437225
b :  [-1.6099461]
hypothesis :  [[0.1665961 ]
 [0.31697354]
 [0.24995358]


In [68]:
w

array([[0.5653667 ],
       [0.88498694]], dtype=float32)

In [69]:
b

array([-1.6689022], dtype=float32)

In [70]:
np.dot(X,w)+b

array([[-1.6689022 ],
       [-0.7839152 ],
       [-1.1035354 ],
       [-0.21854854]], dtype=float32)

In [74]:
predict = sigmoid(np.dot(X,w)+b)
predict

array([[0.1585706 ],
       [0.31347668],
       [0.24907805],
       [0.44557932]], dtype=float32)

In [75]:
predict01 = tf.cast(predict > 0.5, dtype=tf.float32)
print('-'*30)
print(predict01)

------------------------------
tf.Tensor(
[[0.]
 [0.]
 [0.]
 [0.]], shape=(4, 1), dtype=float32)


In [76]:
ac01=tf.equal(predict01,y)
ac01

<tf.Tensor: id=4, shape=(4, 1), dtype=bool, numpy=
array([[ True],
       [ True],
       [ True],
       [False]])>