In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
import tensorflow as tf

C:\ai\python\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\ai\python\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\ai\python\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\ai\python\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type

In [2]:
tf.enable_eager_execution()

In [3]:
data=datasets.load_breast_cancer()
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [4]:
X = data.data
X.shape

(569, 30)

In [5]:
X=np.array(X,dtype='float32')

In [6]:
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]], dtype=float32)

In [7]:
y=data.target
y=np.array(y,dtype='float32')
print(y.shape)
y

(569,)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1.,
       1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1.,
       1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1.,
       0., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1.,
       1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1.,
       1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0.,
       1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1.,
       1., 1., 0., 1., 1.

In [8]:
y=y.reshape(569,1) # 1차원 배열을 2차원 배열로 변환
print(y.shape)
y

(569, 1)


array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],

In [9]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2,random_state=1) 
#X_train에 X중80%, X_test에 X중20%, y_train에 y중80%, y_test에 y중20% 로 나누어지는것

In [10]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(455, 30)
(114, 30)
(455, 1)
(114, 1)


In [11]:
X_train

array([[1.799e+01, 2.066e+01, 1.178e+02, ..., 1.974e-01, 3.060e-01,
        8.503e-02],
       [2.029e+01, 1.434e+01, 1.351e+02, ..., 1.625e-01, 2.364e-01,
        7.678e-02],
       [9.000e+00, 1.440e+01, 5.636e+01, ..., 1.389e-02, 2.991e-01,
        7.804e-02],
       ...,
       [1.720e+01, 2.452e+01, 1.142e+02, ..., 1.899e-01, 3.313e-01,
        1.339e-01],
       [1.403e+01, 2.125e+01, 8.979e+01, ..., 7.963e-02, 2.226e-01,
        7.617e-02],
       [1.303e+01, 1.842e+01, 8.261e+01, ..., 5.013e-02, 1.987e-01,
        6.169e-02]], dtype=float32)

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [14]:
X_train=scaler.transform(X_train)
X_train

array([[ 1.044985  ,  0.29708508,  1.0104483 , ...,  1.2183979 ,
         0.29811844,  0.08380719],
       [ 1.681411  , -1.1409817 ,  1.703381  , ...,  0.69716364,
        -0.8859504 , -0.41234753],
       [-1.4426086 , -1.1273292 , -1.4504637 , ..., -1.5223377 ,
         0.1807326 , -0.3365713 ],
       ...,
       [ 0.82638705,  1.1753982 ,  0.86625403, ...,  1.1063848 ,
         0.7285342 ,  3.0228484 ],
       [-0.05077364,  0.431335  , -0.11146161, ..., -0.5405058 ,
        -1.1207227 , -0.449033  ],
       [-0.32748038, -0.21260943, -0.39904866, ..., -0.98109066,
        -1.527321  , -1.3198599 ]], dtype=float32)

In [15]:
initializer = tf.contrib.layers.xavier_initializer()
w=tf.Variable(initializer([30,1]))
print(w)
b=tf.Variable(initializer([1]))
print(b)

The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

<tf.Variable 'Variable:0' shape=(30, 1) dtype=float32, numpy=
array([[ 0.13355827],
       [ 0.00383541],
       [ 0.25892812],
       [ 0.172063  ],
       [ 0.03768653],
       [-0.30115032],
       [ 0.02527383],
       [-0.16036838],
       [-0.00808242],
       [ 0.08189166],
       [ 0.30811566],
       [ 0.143718  ],
       [ 0.41743314],
       [-0.03420186],
       [ 0.31260622],
       [-0.03674388],
       [ 0.15320575],
       [-0.423204  ],
       [-0.0304212 ],
       [ 0.3544718 ],
       [ 0.01931563],
       [-0.3731218 ],
       [-0.37477547],
       [-0.25974733],
       [ 0.00999141],
       [ 0.4296918 ],
  

In [16]:
tf.matmul(X_train,w)+b

<tf.Tensor: id=35, shape=(455, 1), dtype=float32, numpy=
array([[-1.76460743e-01],
       [ 8.08504999e-01],
       [ 4.69286203e-01],
       [ 4.19331700e-01],
       [-4.87705231e-01],
       [-5.85328102e-01],
       [-3.48726511e-01],
       [-1.14466757e-01],
       [-5.73868394e-01],
       [-9.43237901e-01],
       [-7.42139578e-01],
       [-2.59178519e-01],
       [ 6.70046091e-01],
       [-8.02982211e-01],
       [ 1.73604727e-01],
       [ 2.74453402e+00],
       [-3.47306848e-01],
       [-2.86404997e-01],
       [-5.15505195e-01],
       [ 2.62651539e+00],
       [ 2.53274679e-01],
       [ 1.02581382e+00],
       [-6.71440363e-01],
       [-9.40385222e-01],
       [-1.11869216e+00],
       [ 1.97830200e-02],
       [-1.02497387e+00],
       [ 1.37074858e-01],
       [ 7.69255757e-02],
       [ 1.69359720e+00],
       [-4.62669253e-01],
       [-6.89728796e-01],
       [ 2.27401555e-02],
       [-4.25606608e-01],
       [-8.01188946e-02],
       [ 4.69242394e-01],
       

In [17]:
arr = X_train[0]
arr=arr.reshape(1,30)
arr

array([[ 1.044985  ,  0.29708508,  1.0104483 ,  0.9031281 ,  0.5264205 ,
         0.48808253,  0.3797814 ,  0.9817468 ,  0.6636323 , -0.3025895 ,
         0.14280678, -0.61199456,  0.06991351,  0.16634178,  0.07008423,
         0.10582636, -0.2324402 ,  0.4645556 , -0.7710314 , -0.17532873,
         0.93209964, -0.04698314,  0.8573802 ,  0.75490594,  0.7246325 ,
         0.7589274 ,  0.28422475,  1.2183979 ,  0.29811844,  0.08380719]],
      dtype=float32)

In [18]:
tf.matmul(arr,w)+b

<tf.Tensor: id=41, shape=(1, 1), dtype=float32, numpy=array([[-0.17646074]], dtype=float32)>

In [19]:
hypothesis=tf.sigmoid(tf.matmul(X_train,w)+b)
hypothesis

<tf.Tensor: id=48, shape=(455, 1), dtype=float32, numpy=
array([[0.45599893],
       [0.6917908 ],
       [0.61521477],
       [0.60332334],
       [0.38043433],
       [0.35770753],
       [0.41369128],
       [0.4714145 ],
       [0.3603447 ],
       [0.2802468 ],
       [0.32253647],
       [0.43556565],
       [0.66151345],
       [0.30938798],
       [0.5432925 ],
       [0.9396039 ],
       [0.41403568],
       [0.4288842 ],
       [0.37390387],
       [0.93254864],
       [0.5629823 ],
       [0.73610353],
       [0.3381744 ],
       [0.28082252],
       [0.24625397],
       [0.5049456 ],
       [0.26405966],
       [0.53421515],
       [0.5192219 ],
       [0.84469664],
       [0.3863528 ],
       [0.33409342],
       [0.5056848 ],
       [0.39517593],
       [0.47998098],
       [0.6152044 ],
       [0.21489513],
       [0.49712873],
       [0.46379063],
       [0.83053124],
       [0.48902357],
       [0.5160086 ],
       [0.36874485],
       [0.8800757 ],
       [0.22602335]

In [20]:
optimizer = tf.train.AdamOptimizer(0.001)

In [21]:
for i in range(600):
    with tf.GradientTape() as tape:
        hypothesis = tf.sigmoid(tf.matmul(X_train,w)+b)
        cost = -tf.reduce_mean(y_train*tf.log(hypothesis)+(1-y_train)*tf.log(1-hypothesis))
        print(f'cost{i} :',cost)
        greds = tape.gradient(cost,[w,b])
        print(greds)
    optimizer.apply_gradients(grads_and_vars=zip(greds,[w,b]))
    print('---'*30)

cost0 : tf.Tensor(0.8492326, shape=(), dtype=float32)
[<tf.Tensor: id=105, shape=(30, 1), dtype=float32, numpy=
array([[0.34731698],
       [0.19046299],
       [0.36015892],
       [0.34638202],
       [0.25591624],
       [0.39995322],
       [0.42159465],
       [0.42291602],
       [0.2571209 ],
       [0.12266927],
       [0.33178115],
       [0.0235282 ],
       [0.33231258],
       [0.3051913 ],
       [0.05661905],
       [0.2667381 ],
       [0.22776404],
       [0.2583192 ],
       [0.08877346],
       [0.1620498 ],
       [0.37507144],
       [0.2038393 ],
       [0.38673642],
       [0.36057615],
       [0.28309292],
       [0.39153415],
       [0.41174945],
       [0.4237513 ],
       [0.29060277],
       [0.2963298 ]], dtype=float32)>, <tf.Tensor: id=104, shape=(1,), dtype=float32, numpy=array([-0.10075646], dtype=float32)>]
------------------------------------------------------------------------------------------
cost1 : tf.Tensor(0.8405628, shape=(), dtype=float32)
[<tf

------------------------------------------------------------------------------------------
cost34 : tf.Tensor(0.59863997, shape=(), dtype=float32)
[<tf.Tensor: id=2501, shape=(30, 1), dtype=float32, numpy=
array([[0.25592503],
       [0.13300745],
       [0.26486015],
       [0.25462002],
       [0.18584573],
       [0.28935257],
       [0.309007  ],
       [0.3084032 ],
       [0.18846275],
       [0.08666559],
       [0.24662992],
       [0.00554509],
       [0.24397703],
       [0.22681628],
       [0.04002853],
       [0.18928812],
       [0.16143608],
       [0.17429096],
       [0.06568576],
       [0.11485455],
       [0.27891558],
       [0.14695738],
       [0.28631377],
       [0.26610282],
       [0.2175167 ],
       [0.2950839 ],
       [0.3090619 ],
       [0.31350815],
       [0.23000254],
       [0.229749  ]], dtype=float32)>, <tf.Tensor: id=2500, shape=(1,), dtype=float32, numpy=array([-0.08486857], dtype=float32)>]
------------------------------------------------------

       [ 0.16263576]], dtype=float32)>, <tf.Tensor: id=5053, shape=(1,), dtype=float32, numpy=array([-0.07379415], dtype=float32)>]
------------------------------------------------------------------------------------------
cost72 : tf.Tensor(0.43184087, shape=(), dtype=float32)
[<tf.Tensor: id=5123, shape=(30, 1), dtype=float32, numpy=
array([[ 0.17733136],
       [ 0.08720934],
       [ 0.18218033],
       [ 0.17562085],
       [ 0.11822095],
       [ 0.18414679],
       [ 0.20403366],
       [ 0.20544961],
       [ 0.11874463],
       [ 0.04553835],
       [ 0.16687994],
       [-0.00871504],
       [ 0.16163099],
       [ 0.1537242 ],
       [ 0.01968867],
       [ 0.11148188],
       [ 0.09534889],
       [ 0.09810508],
       [ 0.03482249],
       [ 0.06531673],
       [ 0.195698  ],
       [ 0.10184551],
       [ 0.19872445],
       [ 0.18475132],
       [ 0.1542331 ],
       [ 0.20175347],
       [ 0.21205254],
       [ 0.21427052],
       [ 0.16654515],
       [ 0.16110645]], d

cost106 : tf.Tensor(0.3488136, shape=(), dtype=float32)
[<tf.Tensor: id=7469, shape=(30, 1), dtype=float32, numpy=
array([[ 0.13481174],
       [ 0.0656531 ],
       [ 0.13750257],
       [ 0.133277  ],
       [ 0.07998852],
       [ 0.1256646 ],
       [ 0.14584252],
       [ 0.14925538],
       [ 0.07959297],
       [ 0.02107566],
       [ 0.12334928],
       [-0.01208382],
       [ 0.11785745],
       [ 0.11439692],
       [ 0.00735371],
       [ 0.06715529],
       [ 0.05713806],
       [ 0.05779541],
       [ 0.01805161],
       [ 0.03501133],
       [ 0.15057728],
       [ 0.0803651 ],
       [ 0.15151863],
       [ 0.14148483],
       [ 0.11644645],
       [ 0.14733616],
       [ 0.15628982],
       [ 0.15866438],
       [ 0.12867574],
       [ 0.1181405 ]], dtype=float32)>, <tf.Tensor: id=7468, shape=(1,), dtype=float32, numpy=array([-0.06503272], dtype=float32)>]
------------------------------------------------------------------------------------------
cost107 : tf.Tensor(0.34

       [ 0.08467241]], dtype=float32)>, <tf.Tensor: id=10297, shape=(1,), dtype=float32, numpy=array([-0.05655817], dtype=float32)>]
------------------------------------------------------------------------------------------
cost148 : tf.Tensor(0.28788868, shape=(), dtype=float32)
[<tf.Tensor: id=10367, shape=(30, 1), dtype=float32, numpy=
array([[ 1.02337822e-01],
       [ 5.09975478e-02],
       [ 1.03580870e-01],
       [ 1.00888625e-01],
       [ 5.23292795e-02],
       [ 8.29678699e-02],
       [ 1.02629974e-01],
       [ 1.07708886e-01],
       [ 5.15018255e-02],
       [ 3.70754302e-03],
       [ 9.01111215e-02],
       [-1.13363350e-02],
       [ 8.48203674e-02],
       [ 8.38336349e-02],
       [ 8.58291096e-05],
       [ 3.55353691e-02],
       [ 2.92092897e-02],
       [ 2.99319327e-02],
       [ 6.84488751e-03],
       [ 1.25252604e-02],
       [ 1.16143771e-01],
       [ 6.54006302e-02],
       [ 1.15816295e-01],
       [ 1.08718991e-01],
       [ 8.73893350e-02],
       [ 

       [ 0.06247486]], dtype=float32)>, <tf.Tensor: id=13333, shape=(1,), dtype=float32, numpy=array([-0.0491701], dtype=float32)>]
------------------------------------------------------------------------------------------
cost192 : tf.Tensor(0.24818894, shape=(), dtype=float32)
[<tf.Tensor: id=13403, shape=(30, 1), dtype=float32, numpy=
array([[ 8.0756530e-02],
       [ 4.1805234e-02],
       [ 8.1209585e-02],
       [ 7.9391301e-02],
       [ 3.5857081e-02],
       [ 5.6907326e-02],
       [ 7.5676471e-02],
       [ 8.1503130e-02],
       [ 3.4675311e-02],
       [-5.5723409e-03],
       [ 6.8894923e-02],
       [-9.1796070e-03],
       [ 6.3836090e-02],
       [ 6.3898765e-02],
       [-2.4561349e-03],
       [ 1.7514866e-02],
       [ 1.3282834e-02],
       [ 1.4545169e-02],
       [ 1.0313889e-03],
       [-2.1481397e-05],
       [ 9.3215041e-02],
       [ 5.5600554e-02],
       [ 9.2248529e-02],
       [ 8.7025858e-02],
       [ 6.8677805e-02],
       [ 7.8520775e-02],
       [ 8

[<tf.Tensor: id=16094, shape=(30, 1), dtype=float32, numpy=
array([[ 0.06761403],
       [ 0.03617982],
       [ 0.06768197],
       [ 0.06640884],
       [ 0.02696658],
       [ 0.04241582],
       [ 0.06045607],
       [ 0.0663288 ],
       [ 0.02544507],
       [-0.00964442],
       [ 0.05696505],
       [-0.00717985],
       [ 0.05209491],
       [ 0.05255846],
       [-0.00266539],
       [ 0.00848741],
       [ 0.00564557],
       [ 0.00715476],
       [-0.00134384],
       [-0.00571035],
       [ 0.07912377],
       [ 0.04930263],
       [ 0.07786647],
       [ 0.0737818 ],
       [ 0.05757837],
       [ 0.06267887],
       [ 0.07006817],
       [ 0.07335646],
       [ 0.0672653 ],
       [ 0.0494264 ]], dtype=float32)>, <tf.Tensor: id=16093, shape=(1,), dtype=float32, numpy=array([-0.0435372], dtype=float32)>]
------------------------------------------------------------------------------------------
cost232 : tf.Tensor(0.22315904, shape=(), dtype=float32)
[<tf.Tensor: id=16163,

cost278 : tf.Tensor(0.20177902, shape=(), dtype=float32)
[<tf.Tensor: id=19337, shape=(30, 1), dtype=float32, numpy=
array([[ 0.0561724 ],
       [ 0.03109871],
       [ 0.05598094],
       [ 0.05520392],
       [ 0.02012172],
       [ 0.03094958],
       [ 0.04822817],
       [ 0.05372927],
       [ 0.01826009],
       [-0.01181763],
       [ 0.04740961],
       [-0.00510538],
       [ 0.04273684],
       [ 0.04340264],
       [-0.00195037],
       [ 0.00225716],
       [ 0.00086945],
       [ 0.0023491 ],
       [-0.00249521],
       [-0.00889033],
       [ 0.0667294 ],
       [ 0.04338207],
       [ 0.06529437],
       [ 0.06219475],
       [ 0.04813048],
       [ 0.04945701],
       [ 0.05676309],
       [ 0.05976643],
       [ 0.05660381],
       [ 0.03915133]], dtype=float32)>, <tf.Tensor: id=19336, shape=(1,), dtype=float32, numpy=array([-0.03791169], dtype=float32)>]
------------------------------------------------------------------------------------------
cost279 : tf.Tensor(0

[<tf.Tensor: id=22304, shape=(30, 1), dtype=float32, numpy=
array([[ 4.8363827e-02],
       [ 2.7442094e-02],
       [ 4.8040923e-02],
       [ 4.7601070e-02],
       [ 1.5973102e-02],
       [ 2.3856921e-02],
       [ 4.0515717e-02],
       [ 4.5491233e-02],
       [ 1.3913151e-02],
       [-1.2436498e-02],
       [ 4.1309390e-02],
       [-3.6378331e-03],
       [ 3.6789753e-02],
       [ 3.7518792e-02],
       [-1.0859119e-03],
       [-9.9791517e-04],
       [-1.1960831e-03],
       [ 5.1715368e-05],
       [-2.7986916e-03],
       [-9.9409614e-03],
       [ 5.8194309e-02],
       [ 3.9000820e-02],
       [ 5.6684960e-02],
       [ 5.4240543e-02],
       [ 4.1805178e-02],
       [ 4.0850230e-02],
       [ 4.8149195e-02],
       [ 5.0776549e-02],
       [ 4.9357034e-02],
       [ 3.2667987e-02]], dtype=float32)>, <tf.Tensor: id=22303, shape=(1,), dtype=float32, numpy=array([-0.03351534], dtype=float32)>]
-------------------------------------------------------------------------------

cost365 : tf.Tensor(0.17357545, shape=(), dtype=float32)
[<tf.Tensor: id=25340, shape=(30, 1), dtype=float32, numpy=
array([[ 0.04211716],
       [ 0.02435066],
       [ 0.04171687],
       [ 0.04153283],
       [ 0.01295515],
       [ 0.01864887],
       [ 0.03472321],
       [ 0.03910984],
       [ 0.01079621],
       [-0.01240008],
       [ 0.03661257],
       [-0.00253598],
       [ 0.03222945],
       [ 0.03297152],
       [-0.00029227],
       [-0.00300623],
       [-0.00212023],
       [-0.00121035],
       [-0.00280701],
       [-0.01010655],
       [ 0.0513189 ],
       [ 0.03523754],
       [ 0.04978059],
       [ 0.0478384 ],
       [ 0.03680344],
       [ 0.03425602],
       [ 0.04157112],
       [ 0.04378107],
       [ 0.04361765],
       [ 0.02783308]], dtype=float32)>, <tf.Tensor: id=25339, shape=(1,), dtype=float32, numpy=array([-0.02962273], dtype=float32)>]
------------------------------------------------------------------------------------------
cost366 : tf.Tensor(0

       [ 0.0243397 ]], dtype=float32)>, <tf.Tensor: id=28237, shape=(1,), dtype=float32, numpy=array([-0.02638692], dtype=float32)>]
------------------------------------------------------------------------------------------
cost408 : tf.Tensor(0.16327475, shape=(), dtype=float32)
[<tf.Tensor: id=28307, shape=(30, 1), dtype=float32, numpy=
array([[ 0.037221  ],
       [ 0.02179423],
       [ 0.03677718],
       [ 0.03677677],
       [ 0.01076369],
       [ 0.01486538],
       [ 0.03040321],
       [ 0.03422826],
       [ 0.00858444],
       [-0.01204645],
       [ 0.03299621],
       [-0.00177744],
       [ 0.02873343],
       [ 0.02946687],
       [ 0.00031216],
       [-0.00422586],
       [-0.00241385],
       [-0.00186687],
       [-0.00270459],
       [-0.00984047],
       [ 0.04589713],
       [ 0.03209619],
       [ 0.04435654],
       [ 0.04278723],
       [ 0.03290232],
       [ 0.02928435],
       [ 0.03661657],
       [ 0.03842809],
       [ 0.03917105],
       [ 0.02426672]]

[<tf.Tensor: id=31412, shape=(30, 1), dtype=float32, numpy=
array([[ 0.03303624],
       [ 0.01950018],
       [ 0.0325671 ],
       [ 0.03270625],
       [ 0.00900161],
       [ 0.01184346],
       [ 0.026849  ],
       [ 0.03013181],
       [ 0.00685552],
       [-0.01152694],
       [ 0.02991649],
       [-0.00123617],
       [ 0.02577081],
       [ 0.02648612],
       [ 0.00076371],
       [-0.00503699],
       [-0.00239502],
       [-0.00222036],
       [-0.0025645 ],
       [-0.00936574],
       [ 0.04123697],
       [ 0.02926042],
       [ 0.03970978],
       [ 0.03843978],
       [ 0.02956654],
       [ 0.02517854],
       [ 0.03251981],
       [ 0.033945  ],
       [ 0.03541134],
       [ 0.02136908]], dtype=float32)>, <tf.Tensor: id=31411, shape=(1,), dtype=float32, numpy=array([-0.02329827], dtype=float32)>]
------------------------------------------------------------------------------------------
cost454 : tf.Tensor(0.15402345, shape=(), dtype=float32)
[<tf.Tensor: id=31481

cost498 : tf.Tensor(0.14649369, shape=(), dtype=float32)
[<tf.Tensor: id=34517, shape=(30, 1), dtype=float32, numpy=
array([[ 0.02957656],
       [ 0.01752064],
       [ 0.02909495],
       [ 0.02933378],
       [ 0.0076163 ],
       [ 0.00949635],
       [ 0.02399603],
       [ 0.0267938 ],
       [ 0.0055379 ],
       [-0.01095255],
       [ 0.02735712],
       [-0.00087817],
       [ 0.02332252],
       [ 0.02401604],
       [ 0.00106239],
       [-0.00555574],
       [-0.00221641],
       [-0.00238382],
       [-0.00242381],
       [-0.00882294],
       [ 0.03736274],
       [ 0.02680239],
       [ 0.03585834],
       [ 0.0348193 ],
       [ 0.0267968 ],
       [ 0.02188697],
       [ 0.02922435],
       [ 0.03030222],
       [ 0.03233002],
       [ 0.01907173]], dtype=float32)>, <tf.Tensor: id=34516, shape=(1,), dtype=float32, numpy=array([-0.02066951], dtype=float32)>]
------------------------------------------------------------------------------------------
cost499 : tf.Tensor(0

------------------------------------------------------------------------------------------
cost542 : tf.Tensor(0.13998078, shape=(), dtype=float32)
[<tf.Tensor: id=37553, shape=(30, 1), dtype=float32, numpy=
array([[ 0.02673434],
       [ 0.01583608],
       [ 0.02624847],
       [ 0.02655641],
       [ 0.00652429],
       [ 0.00767472],
       [ 0.02170409],
       [ 0.02408313],
       [ 0.00453086],
       [-0.01038551],
       [ 0.02523365],
       [-0.00064895],
       [ 0.02130348],
       [ 0.02197411],
       [ 0.00124329],
       [-0.00588269],
       [-0.00197583],
       [-0.00243909],
       [-0.00229577],
       [-0.00828921],
       [ 0.03416267],
       [ 0.02470222],
       [ 0.03268568],
       [ 0.03182352],
       [ 0.0245059 ],
       [ 0.01925401],
       [ 0.02657504],
       [ 0.02735175],
       [ 0.02981295],
       [ 0.01724547]], dtype=float32)>, <tf.Tensor: id=37552, shape=(1,), dtype=float32, numpy=array([-0.01842009], dtype=float32)>]
---------------------

cost586 : tf.Tensor(0.13428783, shape=(), dtype=float32)
[<tf.Tensor: id=40589, shape=(30, 1), dtype=float32, numpy=
array([[ 0.02431313],
       [ 0.01435947],
       [ 0.02382827],
       [ 0.02418457],
       [ 0.00562635],
       [ 0.00620292],
       [ 0.01978548],
       [ 0.02179665],
       [ 0.00372682],
       [-0.00983563],
       [ 0.02340317],
       [-0.00049924],
       [ 0.01957396],
       [ 0.02022093],
       [ 0.00134581],
       [-0.00609116],
       [-0.0017148 ],
       [-0.00243366],
       [-0.00217865],
       [-0.00778066],
       [ 0.03142206],
       [ 0.0228538 ],
       [ 0.02997527],
       [ 0.02925354],
       [ 0.02253842],
       [ 0.01706266],
       [ 0.02435632],
       [ 0.0248675 ],
       [ 0.02767409],
       [ 0.0157291 ]], dtype=float32)>, <tf.Tensor: id=40588, shape=(1,), dtype=float32, numpy=array([-0.01644336], dtype=float32)>]
------------------------------------------------------------------------------------------
cost587 : tf.Tensor(0

In [22]:
X_test=scaler.transform(X_test)
X_test

array([[ 0.13185278, -1.2228969 ,  0.2261928 , ..., -0.07497965,
        -0.09827229,  0.5077941 ],
       [-0.28874135, -0.15799935, -0.26406687, ...,  1.3886577 ,
         1.7271669 ,  2.0606084 ],
       [-0.34961691, -0.7587107 , -0.37782013, ..., -0.15264201,
         0.84251803,  0.7339205 ],
       ...,
       [-1.434584  , -0.4606305 , -1.3531326 , ...,  0.8838521 ,
         2.2851768 ,  2.0365524 ],
       [ 0.08757973, -0.00327057,  0.06717876, ..., -0.2969148 ,
        -0.7039168 , -0.54164845],
       [-0.11995033, -0.8110455 , -0.16833808, ..., -1.2351362 ,
        -1.7450807 , -0.93436265]], dtype=float32)

In [23]:
predict = tf.sigmoid(tf.matmul(X_test,w)+b)
predict

<tf.Tensor: id=41506, shape=(114, 1), dtype=float32, numpy=
array([[7.2606635e-01],
       [2.3025742e-01],
       [9.3919218e-01],
       [1.6210467e-01],
       [4.8355997e-01],
       [1.2619358e-01],
       [3.8702428e-02],
       [4.1894409e-01],
       [9.8099798e-01],
       [8.4105015e-01],
       [9.5500839e-01],
       [1.8588549e-01],
       [1.1410785e-01],
       [9.3769515e-01],
       [5.3876579e-01],
       [6.4890832e-01],
       [9.8001587e-01],
       [9.2051971e-01],
       [7.8846091e-01],
       [6.4132422e-02],
       [9.1188288e-01],
       [9.5803928e-01],
       [2.6744515e-02],
       [9.0133667e-01],
       [7.4046791e-02],
       [9.1454315e-01],
       [5.7475245e-01],
       [4.9946874e-02],
       [1.6748905e-05],
       [3.3301491e-01],
       [1.5465915e-03],
       [9.6007043e-01],
       [1.4047146e-02],
       [2.5310001e-01],
       [9.7835070e-01],
       [9.7858012e-01],
       [2.0548937e-01],
       [7.5728631e-01],
       [3.8398778e-01],
    

In [24]:
predict01 = tf.cast(predict>0.5,dtype='float32')
predict01

<tf.Tensor: id=41510, shape=(114, 1), dtype=float32, numpy=
array([[1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
    

In [25]:
tf.reduce_mean(tf.cast(tf.equal(predict01,y_test),dtype='float32'))

<tf.Tensor: id=41516, shape=(), dtype=float32, numpy=0.9736842>