In [1]:
import numpy as np
import tensorflow as tf

C:\ai\python\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\ai\python\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\ai\python\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\ai\python\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type

In [2]:
tf.enable_eager_execution()

In [3]:
X=np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1],
], dtype='float32')
y=np.array([
    [0],
    [1],
    [1],
    [0]
],dtype='float32')

In [4]:
w0 = tf.Variable([
    [1,2],[3,4]
],dtype='float32')

b0 = tf.Variable([
    [0,0]
],dtype='float32')

In [5]:
w1 = tf.Variable([
    [5],[6]
],dtype='float32')
b1 = tf.Variable([
    [0]
],dtype='float32')

In [6]:
optimizer = tf.train.AdamOptimizer(0.1)

In [7]:
for i in range(5000):
    with tf.GradientTape() as tape:
        hyp0 = tf.sigmoid(tf.matmul(X,w0)+b0)
        hyp1 = tf.sigmoid(tf.matmul(hyp0,w1)+b1)
        cost = -tf.reduce_mean(y*tf.log(hyp1)+(1-y)*tf.log(1-hyp1))
        grads = tape.gradient(cost,[w0,w1,b0,b1])
        optimizer.apply_gradients(grads_and_vars=zip(grads,[w0,w1,b0,b1]))
    if i%100 == 0:
        print(f'cost{i}',cost)

cost0 tf.Tensor(4.0991926, shape=(), dtype=float32)
cost100 tf.Tensor(0.5574863, shape=(), dtype=float32)
cost200 tf.Tensor(0.5103298, shape=(), dtype=float32)
cost300 tf.Tensor(0.4952953, shape=(), dtype=float32)
cost400 tf.Tensor(0.48861066, shape=(), dtype=float32)
cost500 tf.Tensor(0.48508033, shape=(), dtype=float32)
cost600 tf.Tensor(0.48299354, shape=(), dtype=float32)
cost700 tf.Tensor(0.4816553, shape=(), dtype=float32)
cost800 tf.Tensor(0.4807425, shape=(), dtype=float32)
cost900 tf.Tensor(0.48008978, shape=(), dtype=float32)
cost1000 tf.Tensor(0.47960454, shape=(), dtype=float32)
cost1100 tf.Tensor(0.47923204, shape=(), dtype=float32)
cost1200 tf.Tensor(0.478938, shape=(), dtype=float32)
cost1300 tf.Tensor(0.4787004, shape=(), dtype=float32)
cost1400 tf.Tensor(0.4785034, shape=(), dtype=float32)
cost1500 tf.Tensor(0.4783359, shape=(), dtype=float32)
cost1600 tf.Tensor(0.47818917, shape=(), dtype=float32)
cost1700 tf.Tensor(0.47805548, shape=(), dtype=float32)
cost1800 tf.Ten

In [8]:
hypothesis = tf.sigmoid(tf.matmul(X,w0)+b0)
hypothesis

<tf.Tensor: id=430171, shape=(4, 2), dtype=float32, numpy=
array([[9.8641241e-01, 7.4630976e-04],
       [9.9999917e-01, 9.9680889e-01],
       [7.8473091e-03, 0.0000000e+00],
       [9.9222112e-01, 1.0018647e-03]], dtype=float32)>

In [9]:
predict=tf.sigmoid(tf.matmul(hypothesis,w1)+b1)
predict

<tf.Tensor: id=430177, shape=(4, 1), dtype=float32, numpy=
array([[1.8140674e-04],
       [9.9982220e-01],
       [9.9967980e-01],
       [1.6501546e-04]], dtype=float32)>

In [10]:
predict =tf.cast(predict>0.5, dtype='float32')
predict

<tf.Tensor: id=430181, shape=(4, 1), dtype=float32, numpy=
array([[0.],
       [1.],
       [1.],
       [0.]], dtype=float32)>

In [11]:
acc = tf.equal(predict,y)
acc

<tf.Tensor: id=430184, shape=(4, 1), dtype=bool, numpy=
array([[ True],
       [ True],
       [ True],
       [ True]])>

In [12]:
acc = tf.cast(acc,dtype='float32')
acc

<tf.Tensor: id=430186, shape=(4, 1), dtype=float32, numpy=
array([[1.],
       [1.],
       [1.],
       [1.]], dtype=float32)>

In [13]:
tf.reduce_mean(acc)

<tf.Tensor: id=430189, shape=(), dtype=float32, numpy=1.0>

In [14]:
arr = np.array([[0,1]],dtype='float32')
arr

array([[0., 1.]], dtype=float32)

In [16]:
hypothesis = tf.sigmoid(tf.matmul(arr,w0)+b0)
predict=tf.sigmoid(tf.matmul(hypothesis,w1)+b1)
predict=tf.cast(predict>0.5, dtype='float32')
predict.numpy()

array([[1.]], dtype=float32)