In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from keras.layers import Dense
from keras.optimizers import Adam
from keras.models import Sequential
import numpy as np

In [3]:
data = datasets.load_breast_cancer()
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [4]:
X = data.data
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [5]:
y = data.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [6]:
X_train, X_test, y_train,y_test = train_test_split(X,y,train_size=0.8)

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
scaler = StandardScaler()

In [12]:
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [13]:
X_train = scaler.transform(X_train)
X_train

array([[-0.06744132, -0.71542049, -0.14685605, ..., -1.01145204,
        -0.54828818, -1.00223254],
       [-0.35512252, -0.23875489, -0.31023706, ..., -0.06190903,
        -0.48493486,  0.2886996 ],
       [-0.8787023 , -0.99308976, -0.8503947 , ..., -0.09295434,
         0.65384108,  0.39504511],
       ...,
       [-0.84993418,  0.4993826 , -0.87290127, ..., -1.04560189,
         0.13909535, -0.71788626],
       [-0.65143415, -0.4146121 , -0.68159544, ..., -0.33096839,
         0.33707448, -0.78385459],
       [-0.8326733 ,  0.14072645, -0.83163923, ..., -1.3832566 ,
         0.63958659, -1.05967049]])

In [14]:
model = Sequential()

In [15]:
model.add(Dense(30,input_dim=30, activation="sigmoid"))

In [17]:
model.add(Dense(10,activation='sigmoid'))

In [18]:
model.add(Dense(1,activation='sigmoid'))

In [19]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 30)                930       
_________________________________________________________________
dense_2 (Dense)              (None, 10)                310       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 11        
Total params: 1,251
Trainable params: 1,251
Non-trainable params: 0
_________________________________________________________________


In [21]:
model.compile(loss='binary_crossentropy',optimizer=Adam(lr=0.0001),metrics=['acc'])

In [22]:
model.fit(X_train,y_train,epochs=1000)


Epoch 1/1000
455/455 [==============================] - 3s 6ms/step - loss: 0.7033 - acc: 0.6308
Epoch 2/1000
455/455 [==============================] - 0s 51us/step - loss: 0.6947 - acc: 0.6308
Epoch 3/1000
455/455 [==============================] - 0s 51us/step - loss: 0.6867 - acc: 0.6308
Epoch 4/1000
455/455 [==============================] - 0s 51us/step - loss: 0.6784 - acc: 0.6308
Epoch 5/1000
455/455 [==============================] - 0s 62us/step - loss: 0.6710 - acc: 0.6308
Epoch 6/1000
455/455 [==============================] - 0s 53us/step - loss: 0.6633 - acc: 0.6308
Epoch 7/1000
455/455 [==============================] - 0s 55us/step - loss: 0.6555 - acc: 0.6308
Epoch 8/1000
455/455 [==============================] - 0s 55us/step - loss: 0.6485 - acc: 0.6308
Epoch 9/1000
455/455 [==============================] - 0s 57us/step - loss: 0.6413 - acc: 0.6308
Epoch 10/1000
455/455 [==============================] - 0s 59us/step - loss: 0.6344 - acc: 0.6308
Epoch 11/1000
455/4

Epoch 82/1000
455/455 [==============================] - 0s 51us/step - loss: 0.2956 - acc: 0.9516
Epoch 83/1000
455/455 [==============================] - 0s 46us/step - loss: 0.2928 - acc: 0.9516
Epoch 84/1000
455/455 [==============================] - 0s 42us/step - loss: 0.2901 - acc: 0.9516
Epoch 85/1000
455/455 [==============================] - 0s 48us/step - loss: 0.2874 - acc: 0.9516
Epoch 86/1000
455/455 [==============================] - 0s 44us/step - loss: 0.2847 - acc: 0.9516
Epoch 87/1000
455/455 [==============================] - 0s 46us/step - loss: 0.2820 - acc: 0.9516
Epoch 88/1000
455/455 [==============================] - 0s 48us/step - loss: 0.2794 - acc: 0.9516
Epoch 89/1000
455/455 [==============================] - 0s 53us/step - loss: 0.2769 - acc: 0.9538
Epoch 90/1000
455/455 [==============================] - 0s 51us/step - loss: 0.2744 - acc: 0.9538
Epoch 91/1000
455/455 [==============================] - 0s 57us/step - loss: 0.2719 - acc: 0.9560
Epoch 92/1

455/455 [==============================] - 0s 53us/step - loss: 0.1584 - acc: 0.9758
Epoch 164/1000
455/455 [==============================] - 0s 57us/step - loss: 0.1574 - acc: 0.9758
Epoch 165/1000
455/455 [==============================] - 0s 59us/step - loss: 0.1565 - acc: 0.9758
Epoch 166/1000
455/455 [==============================] - 0s 70us/step - loss: 0.1555 - acc: 0.9758
Epoch 167/1000
455/455 [==============================] - 0s 77us/step - loss: 0.1545 - acc: 0.9758
Epoch 168/1000
455/455 [==============================] - 0s 62us/step - loss: 0.1536 - acc: 0.9758
Epoch 169/1000
455/455 [==============================] - 0s 73us/step - loss: 0.1527 - acc: 0.9758
Epoch 170/1000
455/455 [==============================] - 0s 51us/step - loss: 0.1517 - acc: 0.9758
Epoch 171/1000
455/455 [==============================] - 0s 57us/step - loss: 0.1508 - acc: 0.9758
Epoch 172/1000
455/455 [==============================] - 0s 70us/step - loss: 0.1500 - acc: 0.9758
Epoch 173/1000


455/455 [==============================] - 0s 44us/step - loss: 0.1034 - acc: 0.9846
Epoch 246/1000
455/455 [==============================] - 0s 48us/step - loss: 0.1029 - acc: 0.9846
Epoch 247/1000
455/455 [==============================] - 0s 48us/step - loss: 0.1025 - acc: 0.9846
Epoch 248/1000
455/455 [==============================] - 0s 48us/step - loss: 0.1021 - acc: 0.9846
Epoch 249/1000
455/455 [==============================] - 0s 42us/step - loss: 0.1017 - acc: 0.9846
Epoch 250/1000
455/455 [==============================] - 0s 46us/step - loss: 0.1012 - acc: 0.9846
Epoch 251/1000
455/455 [==============================] - 0s 42us/step - loss: 0.1008 - acc: 0.9846
Epoch 252/1000
455/455 [==============================] - 0s 51us/step - loss: 0.1004 - acc: 0.9846
Epoch 253/1000
455/455 [==============================] - 0s 48us/step - loss: 0.1000 - acc: 0.9846
Epoch 254/1000
455/455 [==============================] - 0s 51us/step - loss: 0.0996 - acc: 0.9846
Epoch 255/1000


455/455 [==============================] - 0s 51us/step - loss: 0.0765 - acc: 0.9890
Epoch 328/1000
455/455 [==============================] - 0s 57us/step - loss: 0.0763 - acc: 0.9890
Epoch 329/1000
455/455 [==============================] - 0s 51us/step - loss: 0.0760 - acc: 0.9890
Epoch 330/1000
455/455 [==============================] - 0s 70us/step - loss: 0.0758 - acc: 0.9890
Epoch 331/1000
455/455 [==============================] - 0s 55us/step - loss: 0.0755 - acc: 0.9890
Epoch 332/1000
455/455 [==============================] - 0s 68us/step - loss: 0.0753 - acc: 0.9890
Epoch 333/1000
455/455 [==============================] - 0s 57us/step - loss: 0.0751 - acc: 0.9890
Epoch 334/1000
455/455 [==============================] - 0s 57us/step - loss: 0.0749 - acc: 0.9890
Epoch 335/1000
455/455 [==============================] - 0s 70us/step - loss: 0.0746 - acc: 0.9890
Epoch 336/1000
455/455 [==============================] - 0s 55us/step - loss: 0.0744 - acc: 0.9890
Epoch 337/1000


455/455 [==============================] - 0s 66us/step - loss: 0.0614 - acc: 0.9912
Epoch 409/1000
455/455 [==============================] - 0s 64us/step - loss: 0.0613 - acc: 0.9912
Epoch 410/1000
455/455 [==============================] - 0s 62us/step - loss: 0.0611 - acc: 0.9912
Epoch 411/1000
455/455 [==============================] - 0s 59us/step - loss: 0.0611 - acc: 0.9912
Epoch 412/1000
455/455 [==============================] - 0s 59us/step - loss: 0.0608 - acc: 0.9912
Epoch 413/1000
455/455 [==============================] - 0s 66us/step - loss: 0.0607 - acc: 0.9912
Epoch 414/1000
455/455 [==============================] - 0s 57us/step - loss: 0.0606 - acc: 0.9912
Epoch 415/1000
455/455 [==============================] - 0s 64us/step - loss: 0.0605 - acc: 0.9912
Epoch 416/1000
455/455 [==============================] - 0s 64us/step - loss: 0.0603 - acc: 0.9912
Epoch 417/1000
455/455 [==============================] - 0s 79us/step - loss: 0.0602 - acc: 0.9912
Epoch 418/1000


455/455 [==============================] - 0s 77us/step - loss: 0.0519 - acc: 0.9912
Epoch 491/1000
455/455 [==============================] - 0s 53us/step - loss: 0.0518 - acc: 0.9912
Epoch 492/1000
455/455 [==============================] - 0s 66us/step - loss: 0.0517 - acc: 0.9912
Epoch 493/1000
455/455 [==============================] - 0s 57us/step - loss: 0.0516 - acc: 0.9912
Epoch 494/1000
455/455 [==============================] - 0s 64us/step - loss: 0.0515 - acc: 0.9912
Epoch 495/1000
455/455 [==============================] - 0s 55us/step - loss: 0.0514 - acc: 0.9912
Epoch 496/1000
455/455 [==============================] - 0s 64us/step - loss: 0.0513 - acc: 0.9912
Epoch 497/1000
455/455 [==============================] - 0s 57us/step - loss: 0.0512 - acc: 0.9912
Epoch 498/1000
455/455 [==============================] - 0s 75us/step - loss: 0.0511 - acc: 0.9912
Epoch 499/1000
455/455 [==============================] - 0s 59us/step - loss: 0.0511 - acc: 0.9912
Epoch 500/1000


455/455 [==============================] - 0s 68us/step - loss: 0.0454 - acc: 0.9912
Epoch 573/1000
455/455 [==============================] - 0s 64us/step - loss: 0.0453 - acc: 0.9912
Epoch 574/1000
455/455 [==============================] - 0s 94us/step - loss: 0.0452 - acc: 0.9912
Epoch 575/1000
455/455 [==============================] - 0s 68us/step - loss: 0.0452 - acc: 0.9912
Epoch 576/1000
455/455 [==============================] - 0s 64us/step - loss: 0.0451 - acc: 0.9912
Epoch 577/1000
455/455 [==============================] - 0s 53us/step - loss: 0.0451 - acc: 0.9912
Epoch 578/1000
455/455 [==============================] - 0s 73us/step - loss: 0.0450 - acc: 0.9912
Epoch 579/1000
455/455 [==============================] - 0s 57us/step - loss: 0.0449 - acc: 0.9912
Epoch 580/1000
455/455 [==============================] - 0s 70us/step - loss: 0.0448 - acc: 0.9912
Epoch 581/1000
455/455 [==============================] - 0s 64us/step - loss: 0.0448 - acc: 0.9912
Epoch 582/1000


Epoch 654/1000
455/455 [==============================] - 0s 51us/step - loss: 0.0407 - acc: 0.9912
Epoch 655/1000
455/455 [==============================] - 0s 59us/step - loss: 0.0406 - acc: 0.9912
Epoch 656/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0406 - acc: 0.9912
Epoch 657/1000
455/455 [==============================] - 0s 53us/step - loss: 0.0405 - acc: 0.9912
Epoch 658/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0405 - acc: 0.9912
Epoch 659/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0404 - acc: 0.9912
Epoch 660/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0404 - acc: 0.9912
Epoch 661/1000
455/455 [==============================] - 0s 53us/step - loss: 0.0403 - acc: 0.9912
Epoch 662/1000
455/455 [==============================] - 0s 42us/step - loss: 0.0403 - acc: 0.9912
Epoch 663/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0402 - acc: 0.9912


455/455 [==============================] - 0s 40us/step - loss: 0.0372 - acc: 0.9912
Epoch 736/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0372 - acc: 0.9912
Epoch 737/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0371 - acc: 0.9912
Epoch 738/1000
455/455 [==============================] - 0s 40us/step - loss: 0.0371 - acc: 0.9912
Epoch 739/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0371 - acc: 0.9912
Epoch 740/1000
455/455 [==============================] - 0s 62us/step - loss: 0.0370 - acc: 0.9912
Epoch 741/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0369 - acc: 0.9912
Epoch 742/1000
455/455 [==============================] - 0s 51us/step - loss: 0.0369 - acc: 0.9912
Epoch 743/1000
455/455 [==============================] - 0s 51us/step - loss: 0.0369 - acc: 0.9912
Epoch 744/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0368 - acc: 0.9912
Epoch 745/1000


455/455 [==============================] - 0s 57us/step - loss: 0.0343 - acc: 0.9912
Epoch 817/1000
455/455 [==============================] - 0s 77us/step - loss: 0.0342 - acc: 0.9912
Epoch 818/1000
455/455 [==============================] - 0s 51us/step - loss: 0.0342 - acc: 0.9912
Epoch 819/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0342 - acc: 0.9912
Epoch 820/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0341 - acc: 0.9912
Epoch 821/1000
455/455 [==============================] - 0s 51us/step - loss: 0.0341 - acc: 0.9912
Epoch 822/1000
455/455 [==============================] - 0s 51us/step - loss: 0.0341 - acc: 0.9912
Epoch 823/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0340 - acc: 0.9912
Epoch 824/1000
455/455 [==============================] - 0s 42us/step - loss: 0.0340 - acc: 0.9912
Epoch 825/1000
455/455 [==============================] - 0s 51us/step - loss: 0.0340 - acc: 0.9912
Epoch 826/1000


455/455 [==============================] - 0s 53us/step - loss: 0.0318 - acc: 0.9934
Epoch 899/1000
455/455 [==============================] - 0s 51us/step - loss: 0.0318 - acc: 0.9934
Epoch 900/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0317 - acc: 0.9934
Epoch 901/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0317 - acc: 0.9934
Epoch 902/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0316 - acc: 0.9934
Epoch 903/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0316 - acc: 0.9934
Epoch 904/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0316 - acc: 0.9934
Epoch 905/1000
455/455 [==============================] - 0s 53us/step - loss: 0.0316 - acc: 0.9934
Epoch 906/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0315 - acc: 0.9934
Epoch 907/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0315 - acc: 0.9934
Epoch 908/1000


455/455 [==============================] - 0s 53us/step - loss: 0.0296 - acc: 0.9912
Epoch 981/1000
455/455 [==============================] - 0s 59us/step - loss: 0.0296 - acc: 0.9912
Epoch 982/1000
455/455 [==============================] - 0s 51us/step - loss: 0.0296 - acc: 0.9912
Epoch 983/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0295 - acc: 0.9912
Epoch 984/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0295 - acc: 0.9934
Epoch 985/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0295 - acc: 0.9934
Epoch 986/1000
455/455 [==============================] - 0s 51us/step - loss: 0.0295 - acc: 0.9934
Epoch 987/1000
455/455 [==============================] - 0s 51us/step - loss: 0.0294 - acc: 0.9912
Epoch 988/1000
455/455 [==============================] - 0s 51us/step - loss: 0.0294 - acc: 0.9934
Epoch 989/1000
455/455 [==============================] - 0s 59us/step - loss: 0.0294 - acc: 0.9934
Epoch 990/1000


In [24]:
X_test = scaler.transform(X_test)
X_test

array([[ 1.20698637,  0.30732802,  1.20478842, ...,  0.5501271 ,
         0.29431099, -0.29705375],
       [-0.72335445, -0.20636015, -0.7507823 , ..., -0.45692365,
         0.50971228, -0.29705375],
       [-0.69458633, -0.03281685, -0.73202682, ..., -0.83345893,
         0.94843403, -0.81172053],
       ...,
       [-0.16525293, -1.1319244 , -0.18478378, ...,  0.22193382,
         0.14067918, -0.64054407],
       [ 2.63963873,  1.7164996 ,  2.79275185, ...,  2.35814689,
         0.49070628,  0.21420087],
       [ 1.63275454,  1.35784345,  1.60490519, ...,  0.87832039,
         0.66017641,  0.04529918]])

In [36]:
predict = model.predict(X_test)
predict

array([[0.0062224 ],
       [0.9971235 ],
       [0.9973532 ],
       [0.9970485 ],
       [0.99725527],
       [0.9975434 ],
       [0.99742115],
       [0.7538944 ],
       [0.9975076 ],
       [0.9975575 ],
       [0.99727046],
       [0.99737185],
       [0.2606108 ],
       [0.99753535],
       [0.02175546],
       [0.9974822 ],
       [0.99727035],
       [0.9966753 ],
       [0.9957319 ],
       [0.9971479 ],
       [0.9971019 ],
       [0.9968751 ],
       [0.9707924 ],
       [0.9969225 ],
       [0.9969244 ],
       [0.9974934 ],
       [0.08387023],
       [0.00657737],
       [0.00673357],
       [0.00613669],
       [0.99754286],
       [0.00610712],
       [0.01477832],
       [0.399166  ],
       [0.977303  ],
       [0.00611597],
       [0.83201367],
       [0.9967146 ],
       [0.00617489],
       [0.9966502 ],
       [0.99750817],
       [0.00611234],
       [0.00612685],
       [0.00610957],
       [0.15410513],
       [0.99758863],
       [0.99640167],
       [0.006

In [37]:
predict = np.where(predict>0.5,1,0)
predict

array([[0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
    

In [38]:
predict=predict.flatten()
predict

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0])

In [39]:
y_test

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0])

In [40]:
acc = (predict == y_test)
acc

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [41]:
np.average(acc)

0.9736842105263158