In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
from tensorflow.nn import relu
import tensorflow as tf

C:\ai\python\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\ai\python\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\ai\python\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\ai\python\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type

In [2]:
tf.enable_eager_execution()

In [3]:
data = datasets.load_iris()
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
X = data.data
y = data.target
X.shape

(150, 4)

In [5]:
X = np.array(X,dtype="float32")
y = np.array(y,dtype="float32")
y.shape

(150,)

In [6]:
y= y.reshape(150,1)

In [7]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [8]:
from sklearn.preprocessing import OneHotEncoder

In [9]:
enc = OneHotEncoder()

In [10]:
enc.fit(y)

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='error', sparse=True)

In [11]:
enc.transform(y_train).toarray()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1

In [12]:
y_train_onehot = enc.transform(y_train).toarray()
y_train_onehot

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1

In [13]:
y_train_onehot = np.array(y_train_onehot,dtype='float32')
y_train_onehot

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1

In [14]:
y_test_onehot = np.array(enc.transform(y_test).toarray(),dtype='float32')
y_test_onehot

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]], dtype=float32)

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
scaler = StandardScaler()

In [17]:
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [18]:
X_train = scaler.transform(X_train)

In [19]:
initializer = tf.contrib.layers.xavier_initializer()

The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.



In [20]:
w0 = tf.Variable(initializer([4,16]))

In [21]:
w1 = tf.Variable(initializer([16,3]))

In [22]:
b0 = tf.Variable(initializer([16]))

In [23]:
b1 = tf.Variable(initializer([3]))

In [24]:
hypothesis0 = tf.sigmoid(tf.matmul(X_train,w0)+b0)
hypothesis0

<tf.Tensor: id=58, shape=(120, 16), dtype=float32, numpy=
array([[0.3928859 , 0.3757719 , 0.29255152, ..., 0.6396751 , 0.33781993,
        0.34157243],
       [0.50368935, 0.58481795, 0.4642654 , ..., 0.435709  , 0.49391142,
        0.48014936],
       [0.36017007, 0.4513927 , 0.500973  , ..., 0.3682093 , 0.61460173,
        0.47408068],
       ...,
       [0.48245454, 0.52450764, 0.45810813, ..., 0.40090337, 0.51691765,
        0.40139356],
       [0.5072695 , 0.5679119 , 0.4739903 , ..., 0.3943556 , 0.5200309 ,
        0.43814462],
       [0.63172674, 0.687325  , 0.46190852, ..., 0.47480956, 0.3925247 ,
        0.40901393]], dtype=float32)>

In [25]:
hypothesis1 = tf.nn.softmax(tf.matmul(hypothesis0,w1)+b1)
hypothesis1

<tf.Tensor: id=64, shape=(120, 3), dtype=float32, numpy=
array([[0.1957289 , 0.48918894, 0.31508207],
       [0.2151932 , 0.48151115, 0.3032956 ],
       [0.18479082, 0.52685434, 0.28835487],
       [0.17829958, 0.50835145, 0.313349  ],
       [0.30171415, 0.37075946, 0.32752642],
       [0.21775433, 0.48923448, 0.2930112 ],
       [0.20016533, 0.48899257, 0.31084204],
       [0.22381793, 0.4647614 , 0.31142068],
       [0.20214635, 0.48789936, 0.3099543 ],
       [0.2982071 , 0.42341688, 0.27837607],
       [0.27229488, 0.43752143, 0.29018366],
       [0.1856547 , 0.499566  , 0.31477928],
       [0.21062621, 0.46725205, 0.32212168],
       [0.1940632 , 0.5057416 , 0.30019522],
       [0.26259878, 0.44428203, 0.2931192 ],
       [0.25292307, 0.4509407 , 0.29613632],
       [0.20654123, 0.4877583 , 0.30570048],
       [0.21409617, 0.50144845, 0.2844554 ],
       [0.1608692 , 0.5288841 , 0.31024665],
       [0.19509916, 0.49415877, 0.3107421 ],
       [0.20449105, 0.4840491 , 0.31145978]

In [26]:
optimizer = tf.train.AdamOptimizer(0.01)

In [27]:
for i in range(1000):
    with tf.GradientTape() as tape:
        hypothesis0 = tf.sigmoid(tf.matmul(X_train,w0)+b0)
        hypothesis1 = tf.nn.softmax(tf.matmul(hypothesis0,w1)+b1)
        cost = -tf.reduce_sum(y_train_onehot*tf.log(hypothesis1))/len(hypothesis1)
        grads = tape.gradient(cost,[w0,w1,b0,b1])
        optimizer.apply_gradients(grads_and_vars=zip(grads,[w0,w1,b0,b1]))
    if i %100 == 0:
        print(f'cost{i} : {cost.numpy()}')

cost0 : 1.2106341123580933
cost100 : 0.2011779248714447
cost200 : 0.08697617799043655
cost300 : 0.06302151829004288
cost400 : 0.054418642073869705
cost500 : 0.05011583864688873
cost600 : 0.04745900630950928
cost700 : 0.04551326483488083
cost800 : 0.04387470707297325
cost900 : 0.04239176958799362


In [28]:
X_test = scaler.transform(X_test)

In [29]:
hypothesis = tf.sigmoid(tf.matmul(X_test,w0)+b0)
predict = tf.nn.softmax(tf.matmul(hypothesis,w1)+b1)
predict

<tf.Tensor: id=83173, shape=(30, 3), dtype=float32, numpy=
array([[9.9935299e-01, 6.4699579e-04, 1.6439912e-11],
       [9.5176827e-03, 9.9017662e-01, 3.0571513e-04],
       [5.8317441e-04, 9.9939561e-01, 2.1168897e-05],
       [9.9954468e-01, 4.5523950e-04, 1.0293224e-11],
       [1.4008676e-04, 9.9869376e-01, 1.1660728e-03],
       [9.9947447e-01, 5.2552827e-04, 1.2528021e-11],
       [4.5109829e-07, 8.6871744e-04, 9.9913090e-01],
       [2.8323617e-03, 9.9713969e-01, 2.7899820e-05],
       [1.8263427e-07, 3.3810260e-04, 9.9966168e-01],
       [4.9930865e-08, 9.5958094e-05, 9.9990404e-01],
       [3.4971347e-06, 5.5167056e-03, 9.9447978e-01],
       [9.9955195e-01, 4.4797681e-04, 1.0001452e-11],
       [1.7046759e-08, 4.1448446e-05, 9.9995852e-01],
       [2.5964875e-04, 9.9967098e-01, 6.9323673e-05],
       [2.5577184e-03, 9.9742150e-01, 2.0784746e-05],
       [9.9983823e-01, 1.6177501e-04, 5.9063817e-12],
       [2.7859450e-08, 8.6022628e-05, 9.9991393e-01],
       [2.6359310e-04, 

In [30]:
cast_predict = tf.cast(predict>0.5,dtype='float32')
cast_predict

<tf.Tensor: id=83177, shape=(30, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]], dtype=float32)>

In [31]:
arg_predict = tf.argmax(cast_predict,1)
arg_test = tf.argmax(y_test_onehot,1)

In [32]:
tf.equal(arg_predict,arg_test)

<tf.Tensor: id=83184, shape=(30,), dtype=bool, numpy=
array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True])>